# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

ARG ASSEMBLY_VERSION=1.0.0
ARG INFORMATIONAL_VERSION=0.0.0-alpha
ARG DOCKER_VERSION=1.0.0-1-build.1

# Copy the solution file and all project files/folders into the container
COPY . .

RUN echo "AssemblyVersion: ${ASSEMBLY_VERSION}"
RUN echo "InformationalVersion: ${INFORMATIONAL_VERSION}"
RUN echo "DockerVersion: ${DOCKER_VERSION}"

# Restore dependencies for the API project
RUN dotnet restore src/i14y/Bfs.Iop.Iri.Api/Bfs.Iop.Iri.Api.csproj

# Publish the API project
RUN dotnet publish src/i14y/Bfs.Iop.Iri.Api/Bfs.Iop.Iri.Api.csproj -c Release -o /app/publish --no-restore /p:AssemblyVersion=${ASSEMBLY_VERSION} /p:InformationalVersion=${INFORMATIONAL_VERSION}

# Stage 2: Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ARG DOCKER_VERSION=1.0.0-1-build.1

LABEL org.opencontainers.image.version=${DOCKER_VERSION}

ENV APP_VERSION=${DOCKER_VERSION}

# Copy published output from build container
COPY --from=build /app/publish .

# Expose port 80
EXPOSE 80

# Start the API
ENTRYPOINT ["dotnet", "Bfs.Iop.Iri.Api.dll"]