<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Slugify.Core" Version="5.1.1" />
    <PackageReference Include="System.Linq.Async" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bfs.Iop.Core.Abstractions\Bfs.Iop.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.Common\Bfs.Iop.Core.Common.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.Data\Bfs.Iop.Core.Data.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.FileStorage\Bfs.Iop.Core.FileStorage.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.LinkedData\Bfs.Iop.Core.LinkedData.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.Lucene\Bfs.Iop.Core.Lucene.csproj" />
    <ProjectReference Include="..\Bfs.Iop.Core.Elasticsearch\Bfs.Iop.Core.Elasticsearch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).UnitTests" />
    <InternalsVisibleTo Include="$(AssemblyName).Sync" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
