<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591;8625</NoWarn>
		<UserSecretsId>98b7c677-25f8-4c1a-a080-c69bc306270f</UserSecretsId>
		<AssemblyVersion>2.0.0.2</AssemblyVersion>
		<Version>2.0.2</Version>
		<FileVersion>2.0.0.2</FileVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.1" />
		<PackageReference Include="NuGet.Packaging" Version="6.8.0" />
		<PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1" />
		<PackageReference Include="Lamar.Microsoft.DependencyInjection" Version="16.0.0" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="8.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bfs.Iop.Core.Lucene\Bfs.Iop.Core.Lucene.csproj" />
		<ProjectReference Include="..\Bfs.Iop.Core\Bfs.Iop.Core.csproj" />
		<ProjectReference Include="..\..\Infrastructure\Bfs.Iop.Infrastructure.Security\Bfs.Iop.Infrastructure.Security.csproj" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties properties_4launchsettings_1json__JsonSchema="" />
		</VisualStudio>
	</ProjectExtensions>
</Project>
