<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bfs.Iop.Admin.Abstractions\Bfs.Iop.Admin.Abstractions.csproj" />
		<ProjectReference Include="..\..\Core\Bfs.Iop.Core.ApiClient\Bfs.Iop.Core.ApiClient.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Generated\" />
	</ItemGroup>
</Project>