<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
		<IncludeBuildOutput>true</IncludeBuildOutput>
		<IncludeContentInPack>true</IncludeContentInPack>
		<IsPackable>true</IsPackable>
		<OutputType>Library</OutputType>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>Bfs.Iop.Test.Abstraction</PackageId>
		<Version>1.0.1</Version>
		<Authors>Heribert Gasparoli</Authors>
		<Company>Bfs.Iop</Company>
		<Description>Test Abstraction Library für Bfs.Iop</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
		<PackageReference Include="Microsoft.Playwright.NUnit" Version="1.49.0" />
		<PackageReference Include="NUnit" Version="4.6.1" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>

</Project>
