name: i14y-frontend | ABN_PROD_Azure Static Web Apps workflow

on:
  release:
    types: [published]

  push:
    branches: [release/*, Release/*, releases/*, Releases/*]

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the tag version you want to deploy (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  build_and_deploy_job_ABN:
    environment: ABN
    runs-on: ubuntu-latest
    name: Build and Deploy ABN
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: src/frontend/

    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_ACTION_KEY}}
      ENV_NAME: ${{vars.ENV_NAME}}
      RELEASE_VERSION: 1.0.0
      KEYCLOAK_CLIENT_ID: ${{vars.KEYCLOAK_CLIENT_ID}}
      KEYCLOAK_AUTHORITY_URL: ${{vars.KEYCLOAK_AUTHORITY_URL}}
      API_BASE_URL: ${{vars.API_BASE_URL}}
      PARTNER_API_BASE_URL: ${{vars.PARTNER_API_BASE_URL}}
      I14Y_PUBLIC_ROUTE: ${{vars.I14Y_PUBLIC_ROUTE}}
      I14Y_IRI_URL: ${{vars.I14Y_IRI_URL}}
      ADMIN_APP_ROUTE: ${{vars.ADMIN_APP_ROUTE}}
      ANALYTICS_SITE_ID: ${{vars.ANALYTICS_SITE_ID}}
      DASHBOARD_URL: ${{vars.DASHBOARD_URL}}
      IOP_ADMIN_API_BASE_URL: ${{vars.API_BASE_URL}}
      LINK_HANDBOOK: ${{vars.LINK_HANDBOOK}}
      PUBLIC_API_BASE_URL: ${{vars.PUBLIC_API_BASE_URL}}
      SHOW_INFO_VIDEO: ${{vars.SHOW_INFO_VIDEO}}

    steps:
      - name: Check out code from release
        if: github.event_name == 'release'
        uses: actions/checkout@v5
        with:
          submodules: true
          ref: ${{ github.event.release.tag_name }}

      - name: Check out code from release branch
        if: (startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/releases/')) && github.event_name == 'push'
        uses: actions/checkout@v5
        with:
          submodules: true
          ref: ${{ github.ref_name }}

      - name: Check out code from tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Get OIDC token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          check-latest: true

      - name: Install Azure Static Web Apps CLI in admin-ui
        run: npm install -g @azure/static-web-apps-cli  

      - name: Replace variable in appconfig in admin-ui
        run: |
          node -e "
          const fs = require('fs');
          const path = './src/assets/config/appconfig.token.json';
          const outPath = './src/assets/config/appconfig.json';
          let config = fs.readFileSync(path, 'utf8');
          const matches = config.match(/__([A-Z0-9_]+)__/g) || [];
          matches.forEach(token => {
            const varName = token.replace(/__/g, '');
            const value = process.env[varName];
            if (value) {
              console.log(\`Replacing \${token} with value from env \${varName}\`);
              config = config.replace(new RegExp(token, 'g'), value);
            } else {
              console.warn(\`⚠️ Environment variable \${varName} not found, leaving token as-is.\`);
            }
          });
          fs.writeFileSync(outPath, config);
          console.log('✅ Generated', outPath);
          "
        working-directory: src/frontend/admin-ui

      - name: Install dependencies in admin-ui
        run: npm ci --no-audit --no-fund --no-package-lock
        working-directory: src/frontend/admin-ui

      - name: Build Angular in admin-ui
        run: npm run build-prod
        working-directory: src/frontend/admin-ui

      - name: Verify build output in admin-ui
        run: |
          test -f dist/BFS-IOP-ADMIN-UI/browser/index.html
        working-directory: src/frontend/admin-ui



      - name: Deploy to Azure Static Web App in admin-ui
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN_UI }}
        run: |
          echo "🚀 Starting Azure Static Web App deployment..."
          cp staticwebapp.config.json dist/BFS-IOP-ADMIN-UI/browser/;

          # Deploy and capture log
          swa deploy "dist/BFS-IOP-ADMIN-UI/browser/" \
            --env prod \
            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
            --verbose > deploy.log 2>&1
            # Check log for "deployed"

          if grep -q "deployed" deploy.log; then
            echo "✅ Deployment completed successfully."
          else
            echo "❌ Deployment failed. Last 40 lines of log:"
            tail -n 40 deploy.log
            exit 1
          fi
        working-directory: src/frontend/admin-ui

      - name: Replace variable in appconfig in public-ui
        run: |
          node -e "
          const fs = require('fs');
          const path = './src/assets/config/appconfig.token.json';
          const outPath = './src/assets/config/appconfig.json';
          let config = fs.readFileSync(path, 'utf8');
          const matches = config.match(/__([A-Z0-9_]+)__/g) || [];
          matches.forEach(token => {
            const varName = token.replace(/__/g, '');
            const value = process.env[varName];
            if (value) {
              console.log(\`Replacing \${token} with value from env \${varName}\`);
              config = config.replace(new RegExp(token, 'g'), value);
            } else {
              console.warn(\`⚠️ Environment variable \${varName} not found, leaving token as-is.\`);
            }
          });
          fs.writeFileSync(outPath, config);
          console.log('✅ Generated', outPath);
          "
        working-directory: src/frontend/public-ui   


      - name: Install dependencies in public-ui
        run: npm ci --no-audit --no-fund
        working-directory: src/frontend/public-ui          

      - name: Build Angular in public-ui
        run: |
          npm run build-prod;
          test -f dist/browser/index.html
        working-directory: src/frontend/public-ui   


      - name: Deploy to Azure Static Web App in public-ui
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PUBLIC_UI }}
        run: |
          echo "🚀 Starting Azure Static Web App deployment..."
          set -e  # stop script on any unhandled error
          cp staticwebapp.config.json dist/browser/;

          # Deploy and capture log
          swa deploy "dist/browser/" \
            --env prod \
            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
            --verbose > deploy.log 2>&1
            # Check log for "deployed"
            if grep -q "deployed" deploy.log; then
              echo "✅ Deployment completed successfully."
            else
              echo "❌ Deployment failed. Last 40 lines of log:"
              tail -n 40 deploy.log
              exit 1  # mark step as failed
            fi
        working-directory: src/frontend/public-ui


      - name: Upload npm logs artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-abn
          path: ~/.npm/_logs/
          if-no-files-found: ignore
          retention-days: 3

  build_and_deploy_job_PRD:
    environment: PRD
    runs-on: ubuntu-latest
    name: Build and Deploy PRD
    needs: [build_and_deploy_job_ABN]
    permissions:
      id-token: write
      contents: read      
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_ACTION_KEY}}
      ENV_NAME: ${{vars.ENV_NAME}}
      RELEASE_VERSION: 1.0.0
      KEYCLOAK_CLIENT_ID: ${{vars.KEYCLOAK_CLIENT_ID}}
      KEYCLOAK_AUTHORITY_URL: ${{vars.KEYCLOAK_AUTHORITY_URL}}
      API_BASE_URL: ${{vars.API_BASE_URL}}
      PARTNER_API_BASE_URL: ${{vars.PARTNER_API_BASE_URL}}
      I14Y_PUBLIC_ROUTE: ${{vars.I14Y_PUBLIC_ROUTE}}
      I14Y_IRI_URL: ${{vars.I14Y_IRI_URL}}
      ADMIN_APP_ROUTE: ${{vars.ADMIN_APP_ROUTE}}
      ANALYTICS_SITE_ID: ${{vars.ANALYTICS_SITE_ID}}
      DASHBOARD_URL: ${{vars.DASHBOARD_URL}}
      IOP_ADMIN_API_BASE_URL: ${{vars.API_BASE_URL}}
      LINK_HANDBOOK: ${{vars.LINK_HANDBOOK}}
      PUBLIC_API_BASE_URL: ${{vars.PUBLIC_API_BASE_URL}}
      SHOW_INFO_VIDEO: ${{vars.SHOW_INFO_VIDEO}}

    steps:
      - name: Check out code from release
        if: github.event_name == 'release'
        uses: actions/checkout@v5
        with:
          submodules: true
          ref: ${{ github.event.release.tag_name }}

      - name: Check out code from release branch
        if: startsWith(github.ref, 'refs/heads/release/') && github.event_name == 'push'
        uses: actions/checkout@v5
        with:
          submodules: true
          ref: ${{ github.ref_name }}

      - name: Check out code from tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Get OIDC token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          check-latest: true

      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Replace variable in appconfig
        run: |
          node -e "
          const fs = require('fs');
          const path = './src/assets/config/appconfig.token.json';
          const outPath = './src/assets/config/appconfig.json';
          let config = fs.readFileSync(path, 'utf8');
          const matches = config.match(/__([A-Z0-9_]+)__/g) || [];
          matches.forEach(token => {
            const varName = token.replace(/__/g, '');
            const value = process.env[varName];
            if (value) {
              console.log(\`Replacing \${token} with value from env \${varName}\`);
              config = config.replace(new RegExp(token, 'g'), value);
            } else {
              console.warn(\`⚠️ Environment variable \${varName} not found, leaving token as-is.\`);
            }
          });
          fs.writeFileSync(outPath, config);
          console.log('✅ Generated', outPath);
          "
        working-directory: src/frontend/admin-ui

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --no-package-lock
        working-directory: src/frontend/admin-ui

      - name: Build Angular admin-ui
        run: npm run build-prod
        working-directory: src/frontend/admin-ui

      - name: Verify build output admin-ui
        run: |  
          test -f dist/BFS-IOP-ADMIN-UI/browser/index.html
        working-directory: src/frontend/admin-ui

      - name: Deploy to Azure Static Web App admin-ui
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN_UI }}
        run: |
          echo "Starting Azure Static Web App deployment..."
          cp staticwebapp.config.json dist/BFS-IOP-ADMIN-UI/browser/;
          set -e

          swa deploy "dist/BFS-IOP-ADMIN-UI/browser/" \
            --env prod \
            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
            --verbose > deploy.log 2>&1

          if grep -q "deployed" deploy.log; then
            echo "✅ Deployment completed successfully."
          else
            echo "❌ Deployment failed. Last 40 lines of log:"
            tail -n 40 deploy.log
            exit 1
          fi
        working-directory: src/frontend/admin-ui

      - name: Replace variable in appconfig in public-ui
        run: |
          node -e "
          const fs = require('fs');
          const path = './src/assets/config/appconfig.token.json';
          const outPath = './src/assets/config/appconfig.json';
          let config = fs.readFileSync(path, 'utf8');
          const matches = config.match(/__([A-Z0-9_]+)__/g) || [];
          matches.forEach(token => {
            const varName = token.replace(/__/g, '');
            const value = process.env[varName];
            if (value) {
              console.log(\`Replacing \${token} with value from env \${varName}\`);
              config = config.replace(new RegExp(token, 'g'), value);
            } else {
              console.warn(\`⚠️ Environment variable \${varName} not found, leaving token as-is.\`);
            }
          });
          fs.writeFileSync(outPath, config);
          console.log('✅ Generated', outPath);
          "
        working-directory: src/frontend/public-ui   


      - name: Install dependencies in public-ui
        run: npm ci --no-audit --no-fund
        working-directory: src/frontend/public-ui          

      - name: Build Angular in public-ui
        run: |
          npm run build-prod;
          test -f dist/browser/index.html
        working-directory: src/frontend/public-ui 


      - name: Deploy to Azure Static Web App in public-ui
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PUBLIC_UI }}
        run: |
          echo "🚀 Starting Azure Static Web App deployment..."
          set -e  # stop script on any unhandled error
          cp staticwebapp.config.json dist/browser/;

          # Deploy and capture log
          swa deploy "dist/browser/" \
            --env prod \
            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
            --verbose > deploy.log 2>&1
            # Check log for "deployed"
            if grep -q "deployed" deploy.log; then
              echo "✅ Deployment completed successfully."
            else
              echo "❌ Deployment failed. Last 40 lines of log:"
              tail -n 40 deploy.log
              exit 1  # mark step as failed
            fi
        working-directory: src/frontend/public-ui

      - name: Upload npm logs artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs-prd
          path: ~/.npm/_logs/
          if-no-files-found: ignore
          retention-days: 7