name: DEV_Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    environment: DEV
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_ACTION_KEY}}
      ENV_NAME: ${{vars.ENV_NAME}}
      ADMIN_APP_ROUTE: ${{vars.ADMIN_APP_ROUTE}}
      ANALYTICS_SITE_ID: ${{vars.ANALYTICS_SITE_ID}}
      DASHBOARD_URL: ${{vars.DASHBOARD_URL}}
      IOP_ADMIN_API_BASE_URL: ${{vars.IOP_ADMIN_API_BASE_URL}}
      LINK_HANDBOOK: ${{vars.LINK_HANDBOOK}}
      PUBLIC_API_BASE_URL: ${{vars.PUBLIC_API_BASE_URL}}
      SHOW_INFO_VIDEO: ${{vars.SHOW_INFO_VIDEO}}
      I14Y_IRI_URL: ${{vars.I14Y_IRI_URL}}

    steps:
      - uses: actions/checkout@v5
        with:
          lfs: false
          fetch-depth: 0 # needed for GitVersion and tagging
          token: ${{ secrets.DEPLOYMENT_ACTION_KEY}}
          persist-credentials: true

      - name: Get OIDC token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken();
            return token;
          result-encoding: string

      - name: Install GitVersion
        if: github.ref == 'refs/heads/main'
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: "6.*"

      - name: Determine Version
        id: gitversion # step id used as reference for output values
        if: github.ref == 'refs/heads/main'
        uses: gittools/actions/gitversion/execute@v4.1.0
        with:
          disableCache: true
          useConfigFile: true
          updateProjectFiles: true
          logLevel: Error

      - name: Create Version Tag
        id: export
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          git config user.name "robot"
          git config user.email "yujie.zheng@bfs.admin.ch"
          echo "version=${{ steps.gitversion.outputs.MajorMinorPatch }}" >> $GITHUB_OUTPUT
          tag="${{ steps.gitversion.outputs.MajorMinorPatch  }}"

          if git tag -l | grep -q "$tag"; then
           echo "Version tag already exists"
           else
           git tag -a "$tag" -m "Version $tag"
           git push origin "$tag"
           fi

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          check-latest: true
          
  #    - name: Audit packages
  #      run: |
  #        npm audit --json > audit.json || true

  #        echo "📊 Checking vulnerabilities..."
  #        total=$(jq '.metadata.vulnerabilities.total' audit.json)
  #        moderate=$(jq '.metadata.vulnerabilities.moderate' audit.json)
  #        high=$(jq '.metadata.vulnerabilities.high' audit.json)
  #       critical=$(jq '.metadata.vulnerabilities.critical' audit.json)

  #        echo "---------------------------------------------"
  #        echo "🔎 Vulnerability summary:"
  #        echo "   Total:     $total"
  #       echo "   Moderate:  $moderate"
  #        echo "   High:      $high"
  #        echo "   Critical:  $critical"
  #        echo "---------------------------------------------"

     #     if [ "$high" -gt 0 ] || [ "$critical" -gt 0 ]; then
     #       echo "❌ Vulnerabilities detected! (moderate or higher)"
     #       jq '.advisories | to_entries[] | .value | {module_name, severity, title, url}' audit.json
     #       exit 1
     #     else
     #       echo "✅ No high, or critical vulnerabilities found."
     #     fi

      - name: Replace variable in appconfig
        run: |
          node -e "
          const fs = require('fs');
          const path = './src/assets/config/appconfig.token.json';
          const outPath = './src/assets/config/appconfig.json';
          let config = fs.readFileSync(path, 'utf8');
          const matches = config.match(/__([A-Z0-9_]+)__/g) || [];
          matches.forEach(token => {
            const varName = token.replace(/__/g, '');
            const value = process.env[varName];
            if (value) {
              console.log(\`Replacing \${token} with value from env \${varName}\`);
              config = config.replace(new RegExp(token, 'g'), value);
            } else {
              console.warn(\`⚠️ Environment variable \${varName} not found, leaving token as-is.\`);
              config = config.replace(new RegExp(token, 'g'), value);
            }
          });
          fs.writeFileSync(outPath, config);
          console.log('✅ Generated', outPath);
          "

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build Angular
        run: npm run build -- --configuration=production
      - name: Verify build output and copy staticwebapp.config.json
        run: |
          cp staticwebapp.config.json dist/;
          test -f dist/index.html

      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy to Azure Static Web App
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        run: |
          echo "🚀 Starting Azure Static Web App deployment..."
          set -e  # stop script on any unhandled error

          # Deploy and capture log
          swa deploy "dist" \
            --env prod \
            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
            --verbose > deploy.log 2>&1
          # Check log for "deployed"
          if grep -q "deployed" deploy.log; then
            echo "✅ Deployment completed successfully."
          else
            echo "❌ Deployment failed. Last 40 lines of log:"
            tail -n 40 deploy.log
            exit 1  # mark step as failed
          fi
          ###### End of Repository/Build Configurations ######

      - name: Upload npm logs artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs/
          if-no-files-found: ignore
          retention-days: 7