name: i14y-backend | Build & Push Docker Image to ACR | manual trigger
 
on:
  workflow_dispatch:
    inputs:
      overrideNextVersion:
        description: 'Optional GitVersion next-version override (e.g. 1.123.45)'
        required: false
        default: ''
 
permissions:
  id-token: write
  contents: write
  packages: read
 

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME:  iop-core-api
    outputs:
      assembly_version: ${{ steps.export-versions.outputs.assembly_version }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.x'
 
      - name: Determine version
        id: gv
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: false
          additionalArguments: >-
            ${{ github.event_name == 'workflow_dispatch'
                && github.event.inputs.overrideNextVersion != ''
                && format('/overrideconfig next-version={0}', github.event.inputs.overrideNextVersion)
                || '' }}
      - name: Compose & export versions
        id: export-versions
        run: |
            echo "INFORMATIONAL_VERSION=${{ steps.gv.outputs.InformationalVersion }}" >> $GITHUB_ENV
            echo "ASSEMBLY_VERSION=${{ steps.gv.outputs.AssemblySemVer }}" >> $GITHUB_ENV
            echo "DOCKER_VERSION=${{ steps.gv.outputs.SemVer }}-build.${{ github.run_number }}" >> $GITHUB_ENV
            echo "TAG_VERSION=${{ steps.gv.outputs.SemVer }}" >> $GITHUB_ENV
            echo "assembly_version=${{ steps.gv.outputs.AssemblySemVer }}" >> $GITHUB_OUTPUT
 
      - name: Show version
        run: |
            echo "InformationalVersion=$INFORMATIONAL_VERSION"
            echo "AssemblyVersion=$ASSEMBLY_VERSION"
            echo "DockerVersion=$DOCKER_VERSION"
            echo "GitTagVersion=$TAG_VERSION"
 
      - name: Azure Login (UAMI via OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_ACR_UAMI_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_ACR_SUBSCRIPTION_ID }}
 
      - name: Login to ACR
        env:
          AZURE_ACR: ${{ secrets.AZURE_ACR }}
        run: |
          az acr login --name "${AZURE_ACR}"
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Build & push image
        id: buildpush #TODO: change DEPLOYMENT_ACTION_KEY
        env:
          AZURE_ACR_LOGIN_SERVER: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          SHA: ${{ github.sha }}
        run: |
          IMAGE="${AZURE_ACR_LOGIN_SERVER}/${{ env.IMAGE_NAME }}"
          echo "Building and pushing ${IMAGE}:$DOCKER_VERSION, ${IMAGE}:latest, ${IMAGE}:${SHA} and ${IMAGE}:${ASSEMBLY_VERSION}"
 
          docker buildx build src \
            --file Dockerfile.core \
            --push \
            --build-arg ASSEMBLY_VERSION="${ASSEMBLY_VERSION}" \
            --build-arg INFORMATIONAL_VERSION="${INFORMATIONAL_VERSION}" \
            --build-arg DOCKER_VERSION="${DOCKER_VERSION}" \
            --build-arg GithubPackageToken="${{ secrets.DEPLOYMENT_ACTION_KEY }}" \
            --label org.opencontainers.image.version="${DOCKER_VERSION}" \
            --label org.opencontainers.image.revision="${SHA}" \
            -t "${IMAGE}:${DOCKER_VERSION}" \
            -t "${IMAGE}:${SHA}" \
            -t "${IMAGE}:${ASSEMBLY_VERSION}" \
            -t "${IMAGE}:latest"
 
      - name: Tag commit with version
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${TAG_VERSION}" || echo "Tag already exists"
          git push origin "${TAG_VERSION}" || echo "Tag push skipped"
 